name: 🚀 Deploy to Render on changes in /deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'src/deployment/**' 

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: « Trigger Render Build Hook »
        run: |
          echo "Pinging Render build hook…"
          curl -X POST "${{ secrets.RENDER_BUILD_HOOK_URL }}"
